name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build the library
      run: build.bat
      shell: cmd
    - uses: actions/upload-artifact@master
      with:
        name: XamarinAndroidGoldfingerNugetPackage
        path: ./XamarinAndroid.Goldfinger/nupkg
