name: CI

on:
  push:
    branches: 
      - master
    tags:
      - rel/*

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the library
      run: build.bat
      shell: cmd
    - uses: actions/upload-artifact@master
      with:
        name: XamarinAndroidGoldfingerNugetPackage
        path: ./XamarinAndroid.Goldfinger/nupkg

  publish:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/rel/')
    steps:
    - uses: actions/download-artifact@master
      with:
        name: XamarinAndroidGoldfingerNugetPackage
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Nuget Push
      run: nuget push -source https://api.nuget.org/v3/index.json *.nupkg -ApiKey "${{ secrets.NUGET_API_KEY }}"
